<?php
// $Id$
/**
 * @file htmldom.module
 * TODO: Enter file description here.
 */

/**
 * Implementation of hook_elements().
 *
 * These elements represent DOM nodes.
 */
function htmldom_elements() {
  $type['xml_element'] = array(
    '#input' => FALSE,
    '#tag' => '',
    '#attributes' => array(),
    '#pre_render' => array('htmldom_xml_element_pre_render'),
  );
  return $type;
}

/**
 *
 */
function htmldom_xml_element_pre_render($element) {
  if (element_children($element)) {
    $element['#prefix'] = '<'. check_plain($element['#tag']) . drupal_attributes($element['#attributes']) .'>';
    $element['#suffix'] = '</'. check_plain($element['#tag']) .'>';
  }
  else {
    $element['#value'] = '<'. check_plain($element['#tag']) . drupal_attributes($element['#attributes']) .' />';
  }

  // The DOM elements should always reduce to markup elements.
  $element['#type'] = 'markup';
  return $element;
}

function htmldom_dom_to_array($domnode) {
  $element = array();
  switch ($domnode->nodeType) {
    case XML_ELEMENT_NODE:
      $element['#type'] = 'xml_element';
      $element['#tag'] = $domnode->nodeName;
      $element['#attributes'] = array();
      foreach ($domnode->attributes as $attribute => $value) {
        $element['#attributes'][$attribute] = $value->value;
      }
      if ($domnode->hasChildNodes()) {
        foreach ($domnode->childNodes as $child) {
          $element[] = htmldom_dom_to_array($child);
        }
      }
      break;
    case XML_COMMENT_NODE:
      $element['#prefix'] = '<!--';
      $element['#suffix'] = '-->';
    case XML_TEXT_NODE:
      $element['#value'] = $domnode->textContent;
      break;
    default:
      break;
  }
  return $element;
}


/*
 * Test code:
$elements = array();
$elements[0] = array(
  '#type' => 'xml_element',
  '#tag' => 'div',
  '#attributes' => array(
    'class' => 'hi',
  ),
);
$elements[0][0] = array(
   '#tag' => 'p',
   '#type' => 'xml_element',
   '#value' => 'Hi',
);
$elements[0][0][0] = array(
  '#tag' => 'img',
  '#type' => 'xml_element',
  '#attributes' => array(
    'src' => 'image.jpg',
  ),
);
dpm(drupal_render($elements));
 */

/*
$output = '<div class="hi"><p>Hi<img src="image.jpg" /></p></div>';
$document = new DOMDocument();
$document->loadHTML($output);
$xml = array();
$nodes = $document->getElementsByTagName('body')->item(0)->childNodes;
for ($i = 0; $i < $nodes->length; $i++) {
  $xml[] = htmldom_dom_to_array($nodes->item($i));
}
dpm($xml);
dpm(drupal_render($xml));
 */
